jdk:
  - oraclejdk8
language: java
#needed as a work around for https://github.com/travis-ci/travis-ci/issues/5227 which is a buffer overflow in openjdk7 due to using IPV6 (due to docker)
before_install:
  - sudo hostname "$(hostname | cut -c1-63)"
  - sed -e "s/^\\(127\\.0\\.0\\.1.*\\)/\\1 $(hostname | cut -c1-63)/" /etc/hosts | sudo tee /etc/hosts
install: /bin/true #skip having travis-ci trying to run assemble
script: "gradle clean check"
