jdk:
  - openjdk7
  - oraclejdk7
  - oraclejdk8
language: java
#needed as a work around for https://github.com/travis-ci/travis-ci/issues/5227 which is a buffer overflow in openjdk7 due to using IPV6 (due to docker)
before_install:
  - sudo hostname "$(hostname | cut -c1-63)"
  - sed -e "s/^\\(127\\.0\\.0\\.1.*\\)/\\1 $(hostname | cut -c1-63)/" /etc/hosts | sudo tee /etc/hosts
script: "gradle clean check -PossrhUsername=foo -PossrhPassword=foo" #need to have these parameters or travis fails to build
