matrix:
  include:
    - os: linux
      jdk: oraclejdk8
      dist: trusty
    - os: linux
      jdk: oraclejdk9
      dist: trusty
    - os: osx
      before_script: 
        - brew update
        - brew install gradle

language: java

#we don't care about having that much git history when building
git:
  depth: 3

#include the conformance suite repo
before_install: "git clone --depth 3 https://github.com/loc-rdc/bagit-conformance-suite.git"
install: true #skip having travis-ci trying te run assemble
script: "./gradlew clean check dependencyCheckUpdate dependencyCheckAnalyze"
after_success: "./gradlew coveralls"
env:
  global:
    - secure: "hxoE+e6yrSkpP9/+04jgaI4o6kJdMk+vz3eVRnxc7xGzWh4D8N9UsEL/iviDdKgaxrKKik1rkD0U8222NbGFNZSfmeL0j5e+LSTm6Wz5FL0n4t75z5kge4dfH33ndoNJsRfc2CknocXflw0R+Vcn6fb3Dk0osMsdZmhgaObf4zI="
before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/
cache:
  directories:
    - $HOME/.gradle/caches/
